/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 -t ./public/gltf/berry.glb 
*/

import * as THREE from 'three';
import React, { useRef, useState } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { useFrame } from '@react-three/fiber';

type GLTFResult = GLTF & {
  nodes: {
    Berry: THREE.Mesh;
  };
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial;
  };
};

interface BerryProps {
  position?: [number, number, number];
  onCollect?: () => void;
  isGolden?: boolean;
  isPurple?: boolean;
  canCollect?: boolean;
}

export function Berry({
  position = [0, 0, 0],
  isGolden = false,
  isPurple = false,
  onCollect,
  ...props
}: BerryProps & JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/berry.glb') as unknown as GLTFResult;

  const berryRef = useRef<THREE.Group>(null);

  const [collected, setCollected] = useState(false);

  const [scale] = useState(() => 0.8 + Math.random() * 0.4);

  useFrame((state) => {
    if (!berryRef.current) return;

    // Gentle floating animation
    berryRef.current.position.y =
      position[1] + Math.sin(state.clock.elapsedTime * 2) * 0.1;
    berryRef.current.rotation.y += 0.01;

    // Find Pikachu in the scene
    const pokemon = state.scene.getObjectByName('pokemon');
    if (!pokemon || collected) return;

    // Check for collection using Pikachu's position
    const distance = Math.sqrt(
      Math.pow(pokemon.position.x - position[0], 2) +
        Math.pow(pokemon.position.z - position[2], 2)
    );

    // Increased collection radius slightly and made collection more lenient
    if (distance < 1.5) {
      setCollected(true);
      // onCollect();
    }
  });

  if (collected) return null;

  // const getBerryColor = () => {
  //   if (isGolden) return '#FFD700';
  //   if (isPurple) return '#800080';
  //   return '#FF0000';
  // };

  // const getBerryMetalness = () => {
  //   if (isGolden) return 0.8;
  //   if (isPurple) return 0.4;
  //   return 0.1;
  // };

  // const getBerryRoughness = () => {
  //   if (isGolden) return 0.2;
  //   if (isPurple) return 0.5;
  //   return 0.8;
  // };
  return (
    <group
      ref={berryRef}
      scale={scale}
      dispose={null}
      position={[position[0], position[1], position[2]]}
      {...props}
    >
      <mesh
        geometry={nodes.Berry.geometry}
        material={materials['Material.001']}
      />
    </group>
  );
}

useGLTF.preload('/berry.glb');
